FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# --- Etapa de producción con Nginx ---
FROM nginx:alpine

# Limpia el contenido por defecto de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia la app Angular compilada a la raíz
COPY --from=build /app/dist/ng-tailadmin/browser /usr/share/nginx/html

# Copia la landing en una subcarpeta
COPY src/assets/landing /usr/share/nginx/html/landing

# Copia la configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]