services:
  frontend:
    container_name: move-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - move-network

  backend:
    container_name: move-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://move_db:5432/move_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - move_db
    networks:
      - move-network

  move_db:
    container_name: move_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: move_db
    volumes:
      - move_db_data:/var/lib/postgresql/data
    networks:
      - move-network

  # Servicio de Cloudflare Tunnel
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --config /home/nonroot/.cloudflared/config.yml run
    volumes:
      - ~/cloudflared:/home/nonroot/.cloudflared
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    network_mode: host

volumes:
  move_db_data:

networks:
  move-network:
    driver: bridge